### ISSUE TITLE
Race condition in Windows service portion of Mordor::daemon

### ISSUE THREAD

**Issue by wjjensen** [mozy/mordor#8]
Hi,

I believe there is a race condition for validity of the ServiceStatus instance declared on the stack of ServiceMain() in daemon.cpp.  Both HandlerEx() and ServiceMain() access this memory, but HandlerEx() is called in the context of a different thread than ServiceMain(), and it is entirely possible for ServiceMain() to return, and thus move the stack pointer below the status instance, before HandlerEx() attempts to use or modify that memory.

This was sometimes throwing exceptions for me during service shutdown.  As a workaround, I declared 'status' as static.

**Comment by ccutrer** [comment]
Sorry it took me so long to notice this - I was extremely busy in December, and then was out for the holidays.  Now fixed in latest next.
